<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP8hewut\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP8hewut/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerP8hewut.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerP8hewut\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerP8hewut\appDevDebugProjectContainer([
    'container.build_hash' => 'P8hewut',
    'container.build_id' => 'b75ce299',
    'container.build_time' => 1584129712,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP8hewut');
